### ISSUE TITLE
font ที่เหมาะกับภาษาไทย

### ISSUE THREAD

**Issue by offchan42** [chakrit/vim-thai-keys#3]
ผมอยากรู้ว่า คุณใช้ฟอนท์ตัวไหนเหรอครับที่ทำให้ Vim มันแสดงภาษาไทยได้สวยๆหน่อย
ผมใช้ ฟอนท์ [Source Code Pro](https://github.com/adobe-fonts/source-code-pro) มันดีแค่กับภาษาอังกฤษอะครับ

**Comment by chakrit** [comment]
Didn't use any krub. I just stick to Source Code Pro too.
