### ISSUE TITLE
ต้องการทำ Keymap VIM สำหรับใช้กับ IntelliJ Idea ต้องติดตั้งยังไงหรอครับ

### ISSUE THREAD

**Issue by fResult** [chakrit/vim-thai-keys#7]
ต้องการทำ Keymap VIM ใน IDE IntelliJ Idea Free Edition ต้องติดตั้ง Plugin ตัวนี้อย่างไรหรอครับ
ใช้งานบน Windows 10 รบกวนติดต่อกลับทาง Styxmaz@gmail.com หน่อยนะครับ

ขอขอบคุณล่วงหน้า

**Comment by offchan42** [comment]
มันไม่สามารถติดตั้งปลั๊กอินได้ ต้องสร้างไฟล์ .ideavimrc ใน user home ครับ
แล้วก๊อปปี้เนื้อหาในไฟล์นี้ไปใส่ https://github.com/chakrit/vim-thai-keys/blob/master/plugin/vim-thai-keys.vim
แล้วก็เปลี่ยน `:map` เป็น `map` เฉยๆ
แต่ผมลองแล้วมันไม่ได้ผล น่าจะเป็นเพราะว่า IdeaVim มันอ่านไฟล์ที่เขียนภาษาไทยไม่ได้

**Comment by fResult** [comment]
> มันไม่สามารถติดตั้งปลั๊กอินได้ ต้องสร้างไฟล์ .ideavimrc ใน user home ครับ
> แล้วก๊อปปี้เนื้อหาในไฟล์นี้ไปใส่ https://github.com/chakrit/vim-thai-keys/blob/master/plugin/vim-thai-keys.vim
> แล้วก็เปลี่ยน `:map` เป็น `map` เฉยๆ
> แต่ผมลองแล้วมันไม่ได้ผล น่าจะเป็นเพราะว่า IdeaVim มันอ่านไฟล์ที่เขียนภาษาไทยไม่ได้

ปัจจุบันใช้ได้แล้วครับ เย้ๆ
